const id = document.getElementById("video")
const btnAlegria = document.getElementById("btnAlegria")
const btnTristeza = document.getElementById("btnTristeza")
const btnMedo = document.getElementById ("btnMedo")
const btnRaiva = document.getElementById ("btnRaiva")
const btnNojo = document.getElementById ("btnNojo")
const btnVergonha = document.getElementById ("btnVergonha")
const btnAnsiedade = document.getElementById ("btnAnsiedade")
const btnTedio = document.getElementById ("btnTedio")
const btnInveja = document.getElementById ("btnInveja")

btnAlegria.addEventListener("click", () => video.src ="alegria.mp4")
btnTristeza.addEventListener("click", () => video.src ="tristeza.mp4")
btnMedo.addEventListener("click", () => video.src ="medo.mp4")
btnRaiva.addEventListener("click", () => video.src ="raiva.mp4")
btnNojo.addEventListener("click", () => video.src ="nojo.mp4")
btnVergonha.addEventListener("click", () =>video.src ="vergonha")
btnAnsiedade.addEventListener("click", () => video.src ="ansiedade")
btnTedio.addEventListener("click", () => video.src ="tedio.mp4")
btnInveja.addEventListener("click", () => video.src ="inveja.mp4")
